<?php

use App\Island;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IslandsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $islands = [
        ['name' => "Alifushi", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Angolhitheemu", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Baarah", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Bandidhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Berinmadhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Bilehdhoo", 'atoll_id' => 5, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Bilehfahi", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Bodufolhudhoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Buruni", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhaandhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhanbidhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhangethi", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dharanboodhoo", 'atoll_id' => 5, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dharavandhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhevvadhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhidhdhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhidhdhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhiffushi", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhiggaru", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhigurah", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhiyadhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhiyamigili", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Dhonfan", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Eydhafushi", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fainu", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fares", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Faresmaathodaa", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Faridhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Feeali", 'atoll_id' => 5, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Feevah", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fehendhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Felidhoo", 'atoll_id' => 20, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fenfushi", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Feridhoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Feydhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Feydhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Filladhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Finey", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Firunbaidhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fiyoaree", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Foakaidhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fodhdhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fonadhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fulhadhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fulidhoo", 'atoll_id' => 20, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Funadhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Fuvahmulah", 'atoll_id' => 8, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gaadhiffushi", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gaadhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gaafaru", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gadhdhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gan", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gemanafushi", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gemendhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Goidhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Goidhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Gulhi", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Guraidhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Guraidhoo", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hangnaameedhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hanimaadhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hathifushi", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Henbadhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Himandhoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hinmafushi", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hinnavaru", 'atoll_id' => 13, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hirilandhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hirimaradhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hithaadhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hithadhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hithadhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hoandedhdhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hoarafushi", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Holhudhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hondaidhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hulhudheli", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hulhudhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Hulhudhuffaaru", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Huraa", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Ihavandhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Inguraidhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Innamaadhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Isdhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kaashidhoo", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kalaidhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kalamaafushi", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kalhaidhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kamadhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kandholhudhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kanditheemu", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kandoodhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kanduhulhudhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kelaa", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kendhikulhudhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kendhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Keyodhoo", 'atoll_id' => 20, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kihaadhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kinbidhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kinolhas", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kolamaafushi", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kolhufushi", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Komandoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kondey", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kudafari", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kudahuvadhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kudarikilu", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kulhiyandhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kulhudhuffushi", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kumundhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kunahandhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kunburudhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kunburudhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kuredhivaru", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kurendhoo", 'atoll_id' => 13, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Kurinbi", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Landhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Lhaimagu", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Lhohi", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maabaidhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maaenboodhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maafaru", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maafushi", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maakandoodhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maakurathu", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maalhendhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maalhos", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maalhos", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maamendhoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maamendhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maamigili", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maarandhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maathodaa", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maaungoodhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maavah", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maavaidhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Madaveli", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Madifushi", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Madifushi", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Madifushi", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maduvvari", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maduvvari", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Magoodhoo", 'atoll_id' => 5, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Magoodhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Magudhdhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mahibadhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Makunudhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Male'", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Manadhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mandhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mandhoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maradhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maradhoo Feydhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Maroshi", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mathiveri", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Meedhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Meedhoo", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Meedhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Miladhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Milandhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Molhadhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mulah", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Muli", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Mundoo", 'atoll_id' => 12, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Muraidhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Naalaafushi", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nadellaa", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Naifaru", 'atoll_id' => 13, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Naivaadhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Narudhoo", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nellaidhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Neykurendhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nilandhoo", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nilandhoo", 'atoll_id' => 5, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nolhivaran", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Nolhivaranfaru", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Noomaraa", 'atoll_id' => 18, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Olhuvelifushi", 'atoll_id' => 13, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Omadhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Omadhoo", 'atoll_id' => 2, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Raiymandhoo", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rakeedhoo", 'atoll_id' => 20, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rasdhoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rasgetheemu", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rasmaadhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rathafandhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Rinbudhoo", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thakandhoo", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thimarafushi", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thinadhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thinadhoo", 'atoll_id' => 20, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thoddoo", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Tholhendhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thulhaadhoo", 'atoll_id' => 3, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thulusdhoo", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Thuraakunu", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Ukulhas", 'atoll_id' => 1, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Uligan", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Ungoofaaru", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Utheemu", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vaadhoo", 'atoll_id' => 7, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vaadhoo", 'atoll_id' => 16, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vaani", 'atoll_id' => 4, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vaikaradhoo", 'atoll_id' => 10, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vandhoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vashafaru", 'atoll_id' => 9, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Velidhoo", 'atoll_id' => 15, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Veymandoo", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Veyvah", 'atoll_id' => 14, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "viligili", 'atoll_id' => 11, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vilingili", 'atoll_id' => 6, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Villingili", 'atoll_id' => 17, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()],
        ['name' => "Vilufushi", 'atoll_id' => 19, 'created_at'=>Carbon::now(), 'updated_at' => Carbon::now()]
        ];

        Island::insert($islands);
        // factory(App\Island::class,1)->create();
    }
}
